@startuml

state Accepting

State Established {
' Normal system
state Receiving : Receive http message
state Processing : Process Request 
state Sending : Send result 

[*] -> Receiving : TCP connection establish
Receiving -> Processing: Receive HTTP Message complete \n or invalid HTTP message
Receiving -> Sending : Invalid HTTP message
Processing -> Sending : Process finish
Sending -> [*] : Send finish
Sending --> Receiving : Send complete\n(persistent connection enable) 

' Error system
Receiving -> [*] : Connection closed
Sending -> [*] : Connection closed
}

state Closing

[*] -> Accepting : Accept is started concurrently\n by the server
Accepting -> Established
Established -> Closing
Closing -> [*]

@enduml