@startuml
[*] --> Nop

' Normal system
Nop --> Setting : Setting button click
Setting --> Nop : Setting confirmed
Nop --> Pumping : Start button click
Pumping --> Nop : Successful completion,\n Canceled,\n JVLink exception (other error)
Nop --> [*] : Terminated

' Error system
Pumping --> Setting : JVOpen exception \n(301:authentication error,\n302: Expired key,\n303 No key set)
Pumping --> [*] : Fatal error

@enduml