@startuml

cloud c {
    database s3 {
        folder html {
            file "index.html" as index
            file "active_ids.js" as ajs
            file "time_chartdrawer.js" as tjs
            file "prob_chartdrawer.js" as pjs
            file "chart.html" as chart
            index .> chart : Race_id as query parameter
            chart --up- tjs

            chart --up- pjs

            folder time_data {
                file "<id1>.json" as tp1
                file "<id2>.json" as tp2
                file "<id3>.json" as tp3
                note right: compressed by \nKernelDensityEstimation
            } 

            folder prob_tansyo_data {
                file "<id1>.json" as pp1
                file "<id2>.json" as pp2
                file "<id3>.json" as pp3
            } 
        }

    }

    file "model.h5" as model
    database everydb2
    control webprovisioner 

    component winprobestimator2
    interface "HTTP/json" as tanp_i

    component timepredictor
    interface "HTTP/json" as tp_i

    folder raw_time_data {
        file "<id1>.json" as rtp1
        file "<id2>.json" as rtp2
        file "<id3>.json" as rtp3
    } 

    folder raw_prob_tansyo_data {
        file "<id1>.json" as rpp1
        file "<id2>.json" as rpp2
        file "<id3>.json" as rpp3
    } 

    winprobestimator2 - tanp_i

    timepredictor - tp_i
    everydb2 --> timepredictor 
    model --> timepredictor

    ajs --- index
    tp3 ---> tjs
    pp3 ---> pjs

    webprovisioner .up.> tp_i : call
    webprovisioner .up.> tanp_i : call
    webprovisioner ..up.> rtp3 : create
    webprovisioner ..up.> rpp3 : create
    webprovisioner ..> tp3 : create
    webprovisioner ..> pp3 : create
    webprovisioner ..> ajs : create
}

@enduml